-- ============================================================
-- SEED DE DESENVOLVIMENTO
-- ============================================================
-- Ainda não existem dados fictícios oficiais.
-- Este arquivo existe para permitir o reset do banco local.
-- ============================================================
